### ISSUE TITLE
Designing/Finding suitable algorithm

### ISSUE THREAD

**Issue by rmit-s3560494-gerald-lim** [rmit-s3560494-gerald-lim/jobsage#2]
Potential algorithm I designed
https://docs.google.com/document/d/1yqJi0klV4hiog-ZHPLwWKXX1slTUFyQbVktFSgSZbHM/edit?usp=sharing

OR

Possible Machine learning
https://github.com/workforce-data-initiative/skills-ml

**Comment by rmit-s3560494-gerald-lim** [comment]
Fuzzy matching algorithm in search for job seekers; they will search for job postings with keywords

**Comment by rmit-s3560494-gerald-lim** [comment]
https://www.datacamp.com/community/tutorials/fuzzy-string-python

**Comment by rmit-s3560494-gerald-lim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Research K-nearest neighbour](https://trello.com/c/A1Jfm584/72-research-k-nearest-neighbour)

**Comment by rmit-s3560494-gerald-lim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Research K-means clustering](https://trello.com/c/GDN09Slz/71-research-k-means-clustering)

**Comment by matthewty** [comment]
Most likely option is K-nearest neighbour. Find data points that that are most similar to the desired point.

**Comment by rmit-s3560494-gerald-lim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Start implementing K-nearest neighbour for proficiency](https://trello.com/c/ifvtTMGJ/75-start-implementing-k-nearest-neighbour-for-proficiency)

**Comment by rmit-s3560494-gerald-lim** [comment]
K-nearest neighbour has been implemented
